version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: localdb
    ports:
      - "5433:5432"
    volumes:
      - postgres18_local_data:/var/lib/postgresql

volumes:
  postgres18_local_data: